# mini_muse Default Configuration
# This file contains the default settings for the mini_muse application

app_name: "mini_muse"
version: "0.1.0"
log_level: "INFO"
log_file: null
config_dir: "~/.config/mini_muse"

# Model Configuration
models:
  # Ollama Settings
  ollama_host: "http://localhost:11434"
  ollama_model: "llama3.1"
  ollama_timeout: 30
  
  # Stable Diffusion Settings
  sd_model_id: "stabilityai/stable-diffusion-3.5-large"
  sd_cache_dir: null
  sd_device: "auto"
  sd_dtype: "float16"
  
  # Default Generation Parameters
  default_width: 1024
  default_height: 1024
  default_steps: 28
  default_guidance: 7.0

# UI Configuration
ui:
  # Display Settings
  image_display_mode: "ascii"
  ascii_width: 80
  ascii_height: 40
  
  # Interface Settings
  theme: "dark"
  show_help: true
  auto_scroll: true
  
  # Keyboard Shortcuts
  shortcuts:
    generate: "ctrl+g"
    enhance: "ctrl+e"
    feedback: "ctrl+f"
    history: "ctrl+h"
    settings: "ctrl+s"
    quit: "ctrl+q"
    help: "f1"

# User Preferences
user:
  # Generation Preferences
  auto_enhance_prompts: true
  save_generation_history: true
  max_history_items: 100
  
  # Style Preferences
  preferred_styles:
    - "photorealistic"
    - "artistic"
  default_negative_prompt: "blurry, low quality, distorted, ugly, bad anatomy"
  
  # File Management
  output_directory: "./outputs"
  image_format: "png"
  compress_history: true
  
  # Upscaling Preferences
  auto_upscale: false
  upscale_only_favorites: true

# Upscaling Configuration
upscaling:
  # Model Settings
  default_model: "realesrgan-x4plus"
  default_scale_factor: 4
  
  # Performance Settings
  tile_size: 400
  tile_padding: 32
  pre_padding: 10
  use_half_precision: true
  
  # Feature Settings
  enable_face_enhancement: false
  auto_face_enhance: false
  
  # Memory Management
  max_memory_usage_mb: 4096
  clear_cache_after_use: true

# Video Generation Configuration
video_generation:
  # HuggingFace Settings
  hf_token: null  # Set your HuggingFace token here
  
  # Stable Diffusion 3.5 Settings
  sd35_version: "3.5-large"
  sd35_steps: 30
  sd35_guidance_scale: 3.5
  
  # Stable Video Diffusion Settings
  svd_version: "svd-xt-1.1"
  svd_frames: 25
  svd_steps: 25
  
  # Performance Settings
  use_tensorrt: true
  use_cuda_graph: false
  default_precision: "fp8"
  
  # Memory Settings
  max_batch_size: 1
  offload_to_cpu: false
  
  # Output Settings
  video_format: "mp4"
  video_quality: "high"
